;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        end-of-visual-line
        kill-region
        kill-visual-line
        org-cycle
        org-delete-char
        org-self-insert-command
        tcl-electric-hash
        upcase-region
        vhdl-electric-comma
        vhdl-electric-dash
        vhdl-electric-period
        vhdl-electric-semicolon
        vhdl-electric-space
        vhdl-electric-tab
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        isearch-forward-symbol-at-point
        mouse-drag-region-rectangle
        next-error
        suspend-frame
        switch-to-buffer
        vhdl-beautify-buffer
        vhdl-compile
        vhdl-electric-quote
        ))
