;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        corfu-quit
        end-of-visual-line
        indent-for-tab-command
        kill-region
        kill-visual-line
        org-cycle
        org-delete-char
        org-self-insert-command
        tcl-electric-brace
        tcl-electric-char
        tcl-electric-hash
        tcl-indent-command
        upcase-region
        vhdl-electric-comma
        vhdl-electric-dash
        vhdl-electric-period
        vhdl-electric-semicolon
        vhdl-electric-space
        vhdl-electric-tab
        wdired--self-insert
        wdired-finish-edit
        whole-line-or-region-comment-dwim-2
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        isearch-forward-symbol-at-point
        mouse-drag-region-rectangle
        next-error
        suspend-frame
        switch-to-buffer
        vhdl-beautify-buffer
        vhdl-compile
        vhdl-electric-quote
        ))
